### ISSUE TITLE
oapi-codegen is a program, not an importable package

### ISSUE THREAD

**Issue by xylo04** [oapi-codegen/oapi-codegen#1704] opened 2024-07-18 15:28 UTC
The README [recommends](https://github.com/oapi-codegen/oapi-codegen/blob/f6622e749b8c59683109c53c4554eaf6e2bb9374/README.md?plain=1#L43) the tools.go pattern for anchoring the `go:generate` command, which in itself is reasonable. However, `go fmt` is unhappy with the [anonymous import](https://github.com/oapi-codegen/oapi-codegen/blob/f6622e749b8c59683109c53c4554eaf6e2bb9374/README.md?plain=1#L54), saying:

```
import "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" is a program, not an importable package
```

Ultimately, I guess this is an annoyance and not a critical bug. What's your guidance, simply ignore this?

**Comment by eliveikis** [comment] 2024-07-19 13:41
Same issue here. Should we be importing a different path?

**Comment by mromaszewicz** [comment] 2024-07-22 17:38
I'd ignore it. Go's behavior changed around this warning, and this is an old package.

The alternative is to install the actual executable in your $PATH and refer to that from `go:generate` but now you have a versioning problem to solve outside of Go.

**Comment by jamietanna** [comment] 2024-07-23 07:06
Where do you see this warning? That's not one I've seen before - what's the Go toolchain version you're using?

**Comment by adibaulia** [comment] 2024-07-24 07:49
I have same issue here with go version 1.22.5 in VS Code as shown in this screen shoot 

![Screenshot 2024-07-24 at 14 45 16](https://github.com/user-attachments/assets/a9db7d65-c41d-4715-a269-33a8ed5162a5)

Is there any solution on this issue?

**Comment by jamietanna** [comment] 2024-07-24 07:53
@adibaulia can you indicate if the same issue comes from `go fmt` locally?

A [minimal reproduction](https://github.com/oapi-codegen/oapi-codegen/blob/main/CONTRIBUTING.md#minimal-reproductions) would be appreciated, as I've not been able to reproduce this, running 

```
go version go1.22.5 linux/amd64
```

**Comment by adibaulia** [comment] 2024-07-24 08:37
@jamietanna How to do the ```go fmt``` locally?

Here is my go version

![Screenshot 2024-07-24 at 15 32 26](https://github.com/user-attachments/assets/ee7b7cac-a0ea-4bc7-9723-5365bf58b157)

I notice something strange. When i open it on GoLand 2024.1.4, there is no warning show in tools.go file.

**Comment by jamietanna** [comment] 2024-07-24 08:53
Via https://go.dev/blog/gofmt

```sh
go fmt -w tools.go
```

**Comment by adibaulia** [comment] 2024-07-24 09:34
I think there is nothing wrong when I do the `gofmt`. I suspect there was an issue on VSCode linter since it shows the warning with `go list` mentioned. CMIIW.

![Screenshot 2024-07-24 at 16 30 36](https://github.com/user-attachments/assets/b6440b3c-d834-4751-8f20-de95975c36fd)

**Comment by jamietanna** [comment] 2024-07-24 09:51
Interesting, it may be that the VSCode extension is running some other linting checks I'm unaware of.

I don't believe the issue resides with this project, so I'll close this - thanks for the report!

**Closed by jamietanna** 2024-07-24 09:51 UTC
