### ISSUE TITLE
Error creating operation definitions (Keycloak Open API)

### ISSUE THREAD

**Issue by wtask** [oapi-codegen/oapi-codegen#1845] opened 2024-11-26 11:02 UTC
Code gen version
```sh
PS C:\Users\webta\Development\local\keycloak-openapi> oapi-codegen -version
github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
v2.4.1
```

Sources:
https://www.keycloak.org/docs-api/latest/rest-api/openapi.json
https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml

Results:
```sh
PS C:\Users\webta\Development\local\keycloak-openapi> oapi-codegen .\openapi.json
error generating code: error creating operation definitions: path '/admin/realms/{realm}/clients/{client-uuid}/roles/{role-name}/composites/clients/{client-uuid}' has 4 positional parameters, but spec has 3 declared
PS C:\Users\webta\Development\local\keycloak-openapi> oapi-codegen .\openapi.yaml
error generating code: error creating operation definitions: path '/admin/realms/{realm}/clients/{client-uuid}/roles/{role-name}/composites/clients/{client-uuid}' has 4 positional parameters, but spec has 3 declared
```

Json definition:
```json
    "/admin/realms/{realm}/clients/{client-uuid}/roles/{role-name}/composites/clients/{client-uuid}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get client-level roles for the client that are in the role's composite",
        "parameters": [
          {
            "name": "client-uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "role-name",
            "in": "path",
            "description": "role's name (not id!)",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RoleRepresentation"
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "name": "realm",
          "in": "path",
          "description": "realm name (not id!)",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ]
    },
```

The problem is the definition describes 3 positional parameters, but one of them (`client-uuid`) is specified twice in the path.

**Comment by jamietanna** [comment] 2024-11-28 09:10
Looks like a duplicate of https://github.com/oapi-codegen/oapi-codegen/issues/1574

**Closed by jamietanna** 2024-11-28 09:10 UTC
